<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>InedoCore</AssemblyName>
    <RootNamespace>Inedo.Extensions</RootNamespace>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Inedo.AssetDirectories" Version="1.0.1" />
    <PackageReference Include="Inedo.DependencyScan" Version="1.5.12" />
    <PackageReference Include="Inedo.SDK" Version="4.0.0-ci.4">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Inedo.UPack" Version="2.1.6" />
    <PackageReference Include="System.DirectoryServices" Version="10.0.3" />
    <PackageReference Include="System.DirectoryServices.Protocols" Version="10.0.3" />
    <PackageReference Include="Novell.Directory.Ldap.NETStandard" Version="4.0.0" />
  </ItemGroup>
</Project>
